# Generated by Django 5.2.6 on 2025-10-24 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_names', models.JSONField(default=list)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_file', models.FileField(blank=True, null=True, upload_to='errors/')),
                ('total_reports', models.IntegerField(default=0)),
                ('total_drives', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('encodings_tried', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='reports.uploadbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
