# Generated by Django 5.2.7 on 2025-10-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_parsingjob_parseerror_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parsingjob',
            new_name='reports_par_created_e20561_idx',
            old_name='reports_par_created_d3a46f_idx',
        ),
        migrations.RenameIndex(
            model_name='parsingjob',
            new_name='reports_par_status_67a9f3_idx',
            old_name='reports_par_status_856aa9_idx',
        ),
        migrations.AlterField(
            model_name='parsingjob',
            name='result_csv',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='results/'),
        ),
        migrations.AlterField(
            model_name='parsingjob',
            name='result_excel',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='results/'),
        ),
    ]
